# Generated by Django 3.2.7 on 2021-09-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=300)),
                ('car_price', models.IntegerField()),
                ('car_color', models.CharField(max_length=200)),
                ('car_topspeed', models.FloatField(default=0)),
                ('car_modelyear', models.IntegerField()),
                ('car_milage', models.FloatField()),
            ],
        ),
    ]
